configuration_generator:
  n: 29
  output_file: "data/configuration_n29.bin"

mem-trainer:
  n: 29
  ising_training_samples_spin_configurations: "data/configuration_n29.bin"
  ising_observation_spin_configurations: "data/encoded_configurations.bin"
  iterations: 10
  evaluation: true
  training:
    alpha: 0.7